# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := box2d
DEFS_Default := 

# Flags passed to both C and C++ files.
CFLAGS_Default := 

# Flags passed to only C (and not C++) files.
CFLAGS_C_Default := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Default := 

INCS_Default := 

OBJS := $(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Collision/Shapes/b2ChainShape.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Collision/Shapes/b2CircleShape.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Collision/Shapes/b2EdgeShape.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Collision/Shapes/b2PolygonShape.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Collision/b2BroadPhase.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Collision/b2CollideCircle.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Collision/b2CollideEdge.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Collision/b2CollidePolygon.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Collision/b2Collision.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Collision/b2Distance.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Collision/b2DynamicTree.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Collision/b2TimeOfImpact.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Common/b2BlockAllocator.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Common/b2Draw.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Common/b2Math.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Common/b2Settings.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Common/b2StackAllocator.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Common/b2Timer.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Dynamics/Contacts/b2ChainAndCircleContact.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Dynamics/Contacts/b2CircleContact.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Dynamics/Contacts/b2Contact.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Dynamics/Contacts/b2ContactSolver.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Dynamics/Contacts/b2EdgeAndCircleContact.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Dynamics/Contacts/b2EdgeAndPolygonContact.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Dynamics/Contacts/b2PolygonContact.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Dynamics/Joints/b2DistanceJoint.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Dynamics/Joints/b2FrictionJoint.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Dynamics/Joints/b2GearJoint.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Dynamics/Joints/b2Joint.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Dynamics/Joints/b2MouseJoint.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Dynamics/Joints/b2PrismaticJoint.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Dynamics/Joints/b2PulleyJoint.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Dynamics/Joints/b2RevoluteJoint.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Dynamics/Joints/b2RopeJoint.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Dynamics/Joints/b2WeldJoint.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Dynamics/Joints/b2WheelJoint.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Dynamics/b2Body.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Dynamics/b2ContactManager.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Dynamics/b2Fixture.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Dynamics/b2Island.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Dynamics/b2World.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Dynamics/b2WorldCallbacks.o \
	$(obj).target/$(TARGET)/../3rdparty/box2d-2.2.1/Box2D/Rope/b2Rope.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Default := 

LIBS := 

$(obj).target/libbox2d.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/libbox2d.a: LIBS := $(LIBS)
$(obj).target/libbox2d.a: TOOLSET := $(TOOLSET)
$(obj).target/libbox2d.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink)

all_deps += $(obj).target/libbox2d.a
# Add target alias
.PHONY: box2d
box2d: $(obj).target/libbox2d.a

# Add target alias to "all" target.
.PHONY: all
all: box2d

