# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := chipmunk
DEFS_Default := 

# Flags passed to both C and C++ files.
CFLAGS_Default := 

# Flags passed to only C (and not C++) files.
CFLAGS_C_Default := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Default := 

INCS_Default := 

OBJS := $(obj).target/$(TARGET)/../3rdparty/chipmunk-5.3.4/src/chipmunk.o \
	$(obj).target/$(TARGET)/../3rdparty/chipmunk-5.3.4/src/constraints/cpConstraint.o \
	$(obj).target/$(TARGET)/../3rdparty/chipmunk-5.3.4/src/constraints/cpDampedRotarySpring.o \
	$(obj).target/$(TARGET)/../3rdparty/chipmunk-5.3.4/src/constraints/cpDampedSpring.o \
	$(obj).target/$(TARGET)/../3rdparty/chipmunk-5.3.4/src/constraints/cpGearJoint.o \
	$(obj).target/$(TARGET)/../3rdparty/chipmunk-5.3.4/src/constraints/cpGrooveJoint.o \
	$(obj).target/$(TARGET)/../3rdparty/chipmunk-5.3.4/src/constraints/cpPinJoint.o \
	$(obj).target/$(TARGET)/../3rdparty/chipmunk-5.3.4/src/constraints/cpPivotJoint.o \
	$(obj).target/$(TARGET)/../3rdparty/chipmunk-5.3.4/src/constraints/cpRatchetJoint.o \
	$(obj).target/$(TARGET)/../3rdparty/chipmunk-5.3.4/src/constraints/cpRotaryLimitJoint.o \
	$(obj).target/$(TARGET)/../3rdparty/chipmunk-5.3.4/src/constraints/cpSimpleMotor.o \
	$(obj).target/$(TARGET)/../3rdparty/chipmunk-5.3.4/src/constraints/cpSlideJoint.o \
	$(obj).target/$(TARGET)/../3rdparty/chipmunk-5.3.4/src/cpArbiter.o \
	$(obj).target/$(TARGET)/../3rdparty/chipmunk-5.3.4/src/cpArray.o \
	$(obj).target/$(TARGET)/../3rdparty/chipmunk-5.3.4/src/cpBB.o \
	$(obj).target/$(TARGET)/../3rdparty/chipmunk-5.3.4/src/cpBody.o \
	$(obj).target/$(TARGET)/../3rdparty/chipmunk-5.3.4/src/cpCollision.o \
	$(obj).target/$(TARGET)/../3rdparty/chipmunk-5.3.4/src/cpHashSet.o \
	$(obj).target/$(TARGET)/../3rdparty/chipmunk-5.3.4/src/cpPolyShape.o \
	$(obj).target/$(TARGET)/../3rdparty/chipmunk-5.3.4/src/cpShape.o \
	$(obj).target/$(TARGET)/../3rdparty/chipmunk-5.3.4/src/cpSpace.o \
	$(obj).target/$(TARGET)/../3rdparty/chipmunk-5.3.4/src/cpSpaceComponent.o \
	$(obj).target/$(TARGET)/../3rdparty/chipmunk-5.3.4/src/cpSpaceHash.o \
	$(obj).target/$(TARGET)/../3rdparty/chipmunk-5.3.4/src/cpSpaceQuery.o \
	$(obj).target/$(TARGET)/../3rdparty/chipmunk-5.3.4/src/cpSpaceStep.o \
	$(obj).target/$(TARGET)/../3rdparty/chipmunk-5.3.4/src/cpVect.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Default := 

LIBS := 

$(obj).target/libchipmunk.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/libchipmunk.a: LIBS := $(LIBS)
$(obj).target/libchipmunk.a: TOOLSET := $(TOOLSET)
$(obj).target/libchipmunk.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink)

all_deps += $(obj).target/libchipmunk.a
# Add target alias
.PHONY: chipmunk
chipmunk: $(obj).target/libchipmunk.a

# Add target alias to "all" target.
.PHONY: all
all: chipmunk

