# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := freetype
DEFS_Default := 

# Flags passed to both C and C++ files.
CFLAGS_Default := 

# Flags passed to only C (and not C++) files.
CFLAGS_C_Default := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Default := 

INCS_Default := 

OBJS := $(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/builds/win32/ftdebug.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/autofit/autofit.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/base/ftbase.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/base/ftbbox.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/base/ftbitmap.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/base/ftfstype.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/base/ftgasp.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/base/ftglyph.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/base/ftgxval.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/base/ftinit.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/base/ftlcdfil.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/base/ftmm.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/base/ftotval.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/base/ftpatent.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/base/ftpfr.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/base/ftstroke.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/base/ftsynth.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/base/ftsystem.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/base/fttype1.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/base/ftwinfnt.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/base/ftxf86.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/bdf/bdf.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/cache/ftcache.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/cff/cff.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/cid/type1cid.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/gzip/ftgzip.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/lzw/ftlzw.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/pcf/pcf.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/pfr/pfr.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/psaux/psaux.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/pshinter/pshinter.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/psnames/psmodule.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/raster/raster.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/sfnt/sfnt.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/smooth/smooth.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/truetype/truetype.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/type1/type1.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/type42/type42.o \
	$(obj).target/$(TARGET)/../3rdparty/freetype-2.4.4/src/winfonts/winfnt.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Default := 

LIBS := 

$(obj).target/libfreetype.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/libfreetype.a: LIBS := $(LIBS)
$(obj).target/libfreetype.a: TOOLSET := $(TOOLSET)
$(obj).target/libfreetype.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink)

all_deps += $(obj).target/libfreetype.a
# Add target alias
.PHONY: freetype
freetype: $(obj).target/libfreetype.a

# Add target alias to "all" target.
.PHONY: all
all: freetype

