# This file is generated by gyp; do not edit.

export builddir_name ?= ./out
.PHONY: all
all:
	$(MAKE) libcrypto box2d jansson libogg libjpg freetype zlib libcurl contrib lua-lib uslscore libvorbis libssl luaext tinyxml expat chipmunk tlsf moaiext-debugger untz glew sqlite libpng moaiext-luaext zipfs moaiext-untz lua hexdump moaicore luac visualinfo glewinfo moai-untz moai work
