# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := libcurl
DEFS_Default := 

# Flags passed to both C and C++ files.
CFLAGS_Default := 

# Flags passed to only C (and not C++) files.
CFLAGS_C_Default := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Default := 

INCS_Default := 

OBJS := $(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/base64.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/connect.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/content_encoding.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/cookie.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/curl_addrinfo.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/curl_memrchr.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/curl_rand.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/curl_sspi.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/dict.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/easy.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/escape.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/file.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/formdata.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/ftp.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/getenv.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/getinfo.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/gtls.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/hash.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/hostares.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/hostasyn.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/hostip.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/hostip4.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/hostip6.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/hostsyn.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/hostthre.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/http.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/http_chunks.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/http_digest.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/http_negotiate.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/http_ntlm.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/if2ip.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/inet_ntop.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/inet_pton.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/krb4.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/krb5.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/ldap.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/llist.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/md5.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/memdebug.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/mprintf.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/multi.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/netrc.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/nonblock.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/nss.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/parsedate.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/progress.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/qssl.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/rawstr.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/security.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/select.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/sendf.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/share.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/slist.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/socks.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/socks_gssapi.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/socks_sspi.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/speedcheck.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/splay.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/ssh.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/sslgen.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/ssluse.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/strdup.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/strequal.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/strerror.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/strtok.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/strtoofft.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/telnet.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/tftp.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/timeval.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/transfer.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/url.o \
	$(obj).target/$(TARGET)/../3rdparty/curl-7.19.7/lib/version.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Default := 

LIBS := 

$(obj).target/libcurl.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/libcurl.a: LIBS := $(LIBS)
$(obj).target/libcurl.a: TOOLSET := $(TOOLSET)
$(obj).target/libcurl.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink)

all_deps += $(obj).target/libcurl.a
# Add target alias
.PHONY: libcurl
libcurl: $(obj).target/libcurl.a

# Add target alias to "all" target.
.PHONY: all
all: libcurl

