# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := libjpg
DEFS_Default := 

# Flags passed to both C and C++ files.
CFLAGS_Default := 

# Flags passed to only C (and not C++) files.
CFLAGS_C_Default := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Default := 

INCS_Default := 

OBJS := $(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jaricom.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jcapimin.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jcapistd.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jcarith.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jccoefct.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jccolor.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jcdctmgr.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jchuff.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jcinit.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jcmainct.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jcmarker.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jcmaster.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jcomapi.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jcparam.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jcprepct.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jcsample.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jctrans.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jdapimin.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jdapistd.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jdarith.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jdatadst.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jdatasrc.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jdcoefct.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jdcolor.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jddctmgr.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jdhuff.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jdinput.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jdmainct.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jdmarker.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jdmaster.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jdmerge.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jdpostct.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jdsample.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jdtrans.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jerror-moai.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jfdctflt.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jfdctfst.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jfdctint.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jidctflt.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jidctfst.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jidctint.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jmemmgr.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jmemnobs.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jquant1.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jquant2.o \
	$(obj).target/$(TARGET)/../3rdparty/jpeg-8c/jutils.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Default := 

LIBS := 

$(obj).target/libjpg.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/libjpg.a: LIBS := $(LIBS)
$(obj).target/libjpg.a: TOOLSET := $(TOOLSET)
$(obj).target/libjpg.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink)

all_deps += $(obj).target/libjpg.a
# Add target alias
.PHONY: libjpg
libjpg: $(obj).target/libjpg.a

# Add target alias to "all" target.
.PHONY: all
all: libjpg

