# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := libvorbis
DEFS_Default := 

# Flags passed to both C and C++ files.
CFLAGS_Default := 

# Flags passed to only C (and not C++) files.
CFLAGS_C_Default := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Default := 

INCS_Default := 

OBJS := $(obj).target/$(TARGET)/../3rdparty/libvorbis-1.3.2/lib/analysis.o \
	$(obj).target/$(TARGET)/../3rdparty/libvorbis-1.3.2/lib/bitrate.o \
	$(obj).target/$(TARGET)/../3rdparty/libvorbis-1.3.2/lib/block.o \
	$(obj).target/$(TARGET)/../3rdparty/libvorbis-1.3.2/lib/codebook.o \
	$(obj).target/$(TARGET)/../3rdparty/libvorbis-1.3.2/lib/envelope.o \
	$(obj).target/$(TARGET)/../3rdparty/libvorbis-1.3.2/lib/floor0.o \
	$(obj).target/$(TARGET)/../3rdparty/libvorbis-1.3.2/lib/floor1.o \
	$(obj).target/$(TARGET)/../3rdparty/libvorbis-1.3.2/lib/info.o \
	$(obj).target/$(TARGET)/../3rdparty/libvorbis-1.3.2/lib/lookup.o \
	$(obj).target/$(TARGET)/../3rdparty/libvorbis-1.3.2/lib/lpc.o \
	$(obj).target/$(TARGET)/../3rdparty/libvorbis-1.3.2/lib/lsp.o \
	$(obj).target/$(TARGET)/../3rdparty/libvorbis-1.3.2/lib/mapping0.o \
	$(obj).target/$(TARGET)/../3rdparty/libvorbis-1.3.2/lib/mdct.o \
	$(obj).target/$(TARGET)/../3rdparty/libvorbis-1.3.2/lib/psy.o \
	$(obj).target/$(TARGET)/../3rdparty/libvorbis-1.3.2/lib/registry.o \
	$(obj).target/$(TARGET)/../3rdparty/libvorbis-1.3.2/lib/res0.o \
	$(obj).target/$(TARGET)/../3rdparty/libvorbis-1.3.2/lib/sharedbook.o \
	$(obj).target/$(TARGET)/../3rdparty/libvorbis-1.3.2/lib/smallft.o \
	$(obj).target/$(TARGET)/../3rdparty/libvorbis-1.3.2/lib/synthesis.o \
	$(obj).target/$(TARGET)/../3rdparty/libvorbis-1.3.2/lib/vorbisenc.o \
	$(obj).target/$(TARGET)/../3rdparty/libvorbis-1.3.2/lib/vorbisfile.o \
	$(obj).target/$(TARGET)/../3rdparty/libvorbis-1.3.2/lib/window.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Default := 

LIBS := 

$(obj).target/libvorbis.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/libvorbis.a: LIBS := $(LIBS)
$(obj).target/libvorbis.a: TOOLSET := $(TOOLSET)
$(obj).target/libvorbis.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink)

all_deps += $(obj).target/libvorbis.a
# Add target alias
.PHONY: libvorbis
libvorbis: $(obj).target/libvorbis.a

# Add target alias to "all" target.
.PHONY: all
all: libvorbis

