# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := lua-lib
DEFS_Default := 

# Flags passed to both C and C++ files.
CFLAGS_Default := 

# Flags passed to only C (and not C++) files.
CFLAGS_C_Default := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Default := 

INCS_Default := 

OBJS := $(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/lapi.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/lauxlib.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/lbaselib.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/lcode.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/ldblib.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/ldebug.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/ldo.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/ldump.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/lfunc.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/lgc.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/linit.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/liolib.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/llex.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/lmathlib.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/lmem.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/loadlib.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/lobject.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/lopcodes.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/loslib.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/lparser.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/lstate.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/lstring.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/lstrlib.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/ltable.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/ltablib.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/ltm.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/lundump.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/lvm.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/lzio.o \
	$(obj).target/$(TARGET)/../3rdparty/lua-5.1.3/src/print.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Default := 

LIBS := 

$(obj).target/liblua-lib.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/liblua-lib.a: LIBS := $(LIBS)
$(obj).target/liblua-lib.a: TOOLSET := $(TOOLSET)
$(obj).target/liblua-lib.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink)

all_deps += $(obj).target/liblua-lib.a
# Add target alias
.PHONY: lua-lib
lua-lib: $(obj).target/liblua-lib.a

# Add target alias to "all" target.
.PHONY: all
all: lua-lib

