# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := luaext
DEFS_Default := 

# Flags passed to both C and C++ files.
CFLAGS_Default := 

# Flags passed to only C (and not C++) files.
CFLAGS_C_Default := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Default := 

INCS_Default := 

OBJS := $(obj).target/$(TARGET)/../3rdparty/luacrypto-0.2.0/src/lcrypto.o \
	$(obj).target/$(TARGET)/../3rdparty/luacurl-1.2.1/luacurl.o \
	$(obj).target/$(TARGET)/../3rdparty/luafilesystem-1.5.0/src/lfs.o \
	$(obj).target/$(TARGET)/../3rdparty/luasocket-2.0.2/src/auxiliar.o \
	$(obj).target/$(TARGET)/../3rdparty/luasocket-2.0.2/src/buffer.o \
	$(obj).target/$(TARGET)/../3rdparty/luasocket-2.0.2/src/except.o \
	$(obj).target/$(TARGET)/../3rdparty/luasocket-2.0.2/src/inet.o \
	$(obj).target/$(TARGET)/../3rdparty/luasocket-2.0.2/src/io.o \
	$(obj).target/$(TARGET)/../3rdparty/luasocket-2.0.2/src/luasocket.o \
	$(obj).target/$(TARGET)/../3rdparty/luasocket-2.0.2/src/mime.o \
	$(obj).target/$(TARGET)/../3rdparty/luasocket-2.0.2/src/options.o \
	$(obj).target/$(TARGET)/../3rdparty/luasocket-2.0.2/src/select.o \
	$(obj).target/$(TARGET)/../3rdparty/luasocket-2.0.2/src/tcp.o \
	$(obj).target/$(TARGET)/../3rdparty/luasocket-2.0.2/src/timeout.o \
	$(obj).target/$(TARGET)/../3rdparty/luasocket-2.0.2/src/udp.o \
	$(obj).target/$(TARGET)/../3rdparty/luasocket-2.0.2/src/wsocket.o \
	$(obj).target/$(TARGET)/../3rdparty/luasql-2.2.0/src/ls_sqlite3.o \
	$(obj).target/$(TARGET)/../3rdparty/luasql-2.2.0/src/luasql.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Default := 

LIBS := 

$(obj).target/libluaext.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/libluaext.a: LIBS := $(LIBS)
$(obj).target/libluaext.a: TOOLSET := $(TOOLSET)
$(obj).target/libluaext.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink)

all_deps += $(obj).target/libluaext.a
# Add target alias
.PHONY: luaext
luaext: $(obj).target/libluaext.a

# Add target alias to "all" target.
.PHONY: all
all: luaext

