# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := moaicore
DEFS_Default := 

# Flags passed to both C and C++ files.
CFLAGS_Default := 

# Flags passed to only C (and not C++) files.
CFLAGS_C_Default := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Default := 

INCS_Default := 

OBJS := $(obj).target/$(TARGET)/../src/aku/AKU-particles.o \
	$(obj).target/$(TARGET)/../src/aku/AKU.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIAction.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIActionMgr.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIAnim.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIAnimCurve.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIBitmapFontRipper.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIBlendMode.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIBlocker.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIBox2DArbiter.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIBox2DBody.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIBox2DDebugDraw.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIBox2DDistanceJoint.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIBox2DFixture.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIBox2DFrictionJoint.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIBox2DGearJoint.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIBox2DJoint.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIBox2DMouseJoint.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIBox2DPrismaticJoint.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIBox2DPulleyJoint.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIBox2DRevoluteJoint.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIBox2DRopeJoint.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIBox2DWeldJoint.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIBox2DWheelJoint.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIBox2DWorld.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIButtonSensor.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAICameraAnchor2D.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAICameraFitter2D.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAICanary.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIColor.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAICompassSensor.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAICoroutine.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAICp.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAICpArbiter.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAICpBody.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAICpConstraint.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAICpDebugDraw.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAICpShape.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAICpSpace.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIDataBuffer.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIDataIOAction.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIDebugLines.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIDeck.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIDeck2D.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIDeckRemapper.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIDeserializer.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIDraw.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIEaseDriver.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIEaseType.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIEnvironment.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIEventSource.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIFileSystem.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIFont.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIFrameBuffer.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIFreetypeFontRipper.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIGfxDevice.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIGfxQuad2D.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIGfxQuadDeck2D.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIGfxQuadListDeck2D.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIGfxResource.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIGlobals.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIGlyph.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIGrid.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIGridPathGraph.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIGridSpace.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIHttpTask.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIHttpTaskInfo_curl.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIImage-jpg.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIImage-png.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIImage.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIIndexBuffer.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIInputDevice.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIInputMgr.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIJoystickSensor.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIJsonParser.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIKeyboardSensor.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAILayer2D.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAILayerBridge2D.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAILayoutFrame.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAILineBrush.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAILocationSensor.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAILogMessages.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAILogMgr.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAILuaObject.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAILuaRef.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAILuaRuntime.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAILuaState.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAILuaStateHandle.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIMesh.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIMotionSensor.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAINode.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAINodeMgr.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIObject.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIParser.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIParticleDistanceEmitter.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIParticleEmitter.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIParticleForce.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIParticlePlugin.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIParticleScript.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIParticleState.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIParticleSystem.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIParticleTimedEmitter.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIPartition.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIPartitionCell.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIPartitionLayer.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIPartitionResultBuffer.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIPartitionResultMgr.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIPathFinder.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIPathGraph.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIPathTerrainDeck.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIPointerSensor.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIProp.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIProp2D.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIQuadBrush.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIRtti.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIScriptDeck.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIScriptNode.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAISensor.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAISerializer.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAISerializerBase.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIShader.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIShaderMgr.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAISim.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIStretchPatch2D.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAISurfaceDeck2D.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAISurfaceSampler2D.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAITextBox.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAITextFrame.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAITextLayout.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAITexture.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAITileDeck2D.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAITileFlags.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAITimer.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAITouchSensor.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAITransform.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAITransformBase.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIUrlMgr_curl.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIVertexBuffer.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIVertexFormat.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIVertexFormatMgr.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIViewport.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIWheelSensor.o \
	$(obj).target/$(TARGET)/../src/moaicore/MOAIXmlParser.o \
	$(obj).target/$(TARGET)/../src/moaicore/moaicore-pch.o \
	$(obj).target/$(TARGET)/../src/moaicore/moaicore.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Default := 

LIBS := 

$(obj).target/libmoaicore.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/libmoaicore.a: LIBS := $(LIBS)
$(obj).target/libmoaicore.a: TOOLSET := $(TOOLSET)
$(obj).target/libmoaicore.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink)

all_deps += $(obj).target/libmoaicore.a
# Add target alias
.PHONY: moaicore
moaicore: $(obj).target/libmoaicore.a

# Add target alias to "all" target.
.PHONY: all
all: moaicore

