# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := untz
DEFS_Default := 

# Flags passed to both C and C++ files.
CFLAGS_Default := 

# Flags passed to only C (and not C++) files.
CFLAGS_C_Default := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Default := 

INCS_Default := 

OBJS := $(obj).target/$(TARGET)/../3rdparty/rtaudio-4.0.8/RtAudio.o \
	$(obj).target/$(TARGET)/../3rdparty/rtaudio-4.0.8/include/asio.o \
	$(obj).target/$(TARGET)/../3rdparty/rtaudio-4.0.8/include/asiodrivers.o \
	$(obj).target/$(TARGET)/../3rdparty/rtaudio-4.0.8/include/asiolist.o \
	$(obj).target/$(TARGET)/../3rdparty/rtaudio-4.0.8/include/iasiothiscallresolver.o \
	$(obj).target/$(TARGET)/../3rdparty/untz/src/AudioMixer.o \
	$(obj).target/$(TARGET)/../3rdparty/untz/src/BufferedAudioSource.o \
	$(obj).target/$(TARGET)/../3rdparty/untz/src/BufferedAudioSourceThread.o \
	$(obj).target/$(TARGET)/../3rdparty/untz/src/MemoryAudioSource.o \
	$(obj).target/$(TARGET)/../3rdparty/untz/src/OggAudioSource.o \
	$(obj).target/$(TARGET)/../3rdparty/untz/src/UntzSound.o \
	$(obj).target/$(TARGET)/../3rdparty/untz/src/UserAudioSource.o \
	$(obj).target/$(TARGET)/../3rdparty/untz/src/native/win/DShowAudioSource.o \
	$(obj).target/$(TARGET)/../3rdparty/untz/src/native/win/UntzSystem.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Default := 

LIBS := 

$(obj).target/libuntz.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/libuntz.a: LIBS := $(LIBS)
$(obj).target/libuntz.a: TOOLSET := $(TOOLSET)
$(obj).target/libuntz.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink)

all_deps += $(obj).target/libuntz.a
# Add target alias
.PHONY: untz
untz: $(obj).target/libuntz.a

# Add target alias to "all" target.
.PHONY: all
all: untz

