# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := uslscore
DEFS_Default := 

# Flags passed to both C and C++ files.
CFLAGS_Default := 

# Flags passed to only C (and not C++) files.
CFLAGS_C_Default := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Default := 

INCS_Default := 

OBJS := $(obj).target/$(TARGET)/../src/uslscore/STLString.o \
	$(obj).target/$(TARGET)/../src/uslscore/USAdapterInfo_win32.o \
	$(obj).target/$(TARGET)/../src/uslscore/USBase64Cipher.o \
	$(obj).target/$(TARGET)/../src/uslscore/USBox.o \
	$(obj).target/$(TARGET)/../src/uslscore/USByteStream.o \
	$(obj).target/$(TARGET)/../src/uslscore/USCgt.o \
	$(obj).target/$(TARGET)/../src/uslscore/USCipher.o \
	$(obj).target/$(TARGET)/../src/uslscore/USCipherStream.o \
	$(obj).target/$(TARGET)/../src/uslscore/USColor.o \
	$(obj).target/$(TARGET)/../src/uslscore/USCurve.o \
	$(obj).target/$(TARGET)/../src/uslscore/USData.o \
	$(obj).target/$(TARGET)/../src/uslscore/USDataIOTask.o \
	$(obj).target/$(TARGET)/../src/uslscore/USDeflater.o \
	$(obj).target/$(TARGET)/../src/uslscore/USDeviceTime_apple.o \
	$(obj).target/$(TARGET)/../src/uslscore/USDeviceTime_posix.o \
	$(obj).target/$(TARGET)/../src/uslscore/USDeviceTime_win32.o \
	$(obj).target/$(TARGET)/../src/uslscore/USDirectoryItr.o \
	$(obj).target/$(TARGET)/../src/uslscore/USDistance.o \
	$(obj).target/$(TARGET)/../src/uslscore/USFileStream.o \
	$(obj).target/$(TARGET)/../src/uslscore/USFileSys.o \
	$(obj).target/$(TARGET)/../src/uslscore/USFilename.o \
	$(obj).target/$(TARGET)/../src/uslscore/USHexDump.o \
	$(obj).target/$(TARGET)/../src/uslscore/USInflater.o \
	$(obj).target/$(TARGET)/../src/uslscore/USInterpolate.o \
	$(obj).target/$(TARGET)/../src/uslscore/USIntersect.o \
	$(obj).target/$(TARGET)/../src/uslscore/USLexStream.o \
	$(obj).target/$(TARGET)/../src/uslscore/USLog.o \
	$(obj).target/$(TARGET)/../src/uslscore/USMemStream.o \
	$(obj).target/$(TARGET)/../src/uslscore/USMercator.o \
	$(obj).target/$(TARGET)/../src/uslscore/USMutex.o \
	$(obj).target/$(TARGET)/../src/uslscore/USMutex_posix.o \
	$(obj).target/$(TARGET)/../src/uslscore/USMutex_win32.o \
	$(obj).target/$(TARGET)/../src/uslscore/USParser.o \
	$(obj).target/$(TARGET)/../src/uslscore/USPlane.o \
	$(obj).target/$(TARGET)/../src/uslscore/USPolar.o \
	$(obj).target/$(TARGET)/../src/uslscore/USQuad.o \
	$(obj).target/$(TARGET)/../src/uslscore/USQuadCoord.o \
	$(obj).target/$(TARGET)/../src/uslscore/USStream.o \
	$(obj).target/$(TARGET)/../src/uslscore/USStreamFormatter.o \
	$(obj).target/$(TARGET)/../src/uslscore/USSurface2D.o \
	$(obj).target/$(TARGET)/../src/uslscore/USSyntaxNode.o \
	$(obj).target/$(TARGET)/../src/uslscore/USSyntaxScanner.o \
	$(obj).target/$(TARGET)/../src/uslscore/USTask.o \
	$(obj).target/$(TARGET)/../src/uslscore/USTaskThread.o \
	$(obj).target/$(TARGET)/../src/uslscore/USThread.o \
	$(obj).target/$(TARGET)/../src/uslscore/USThread_posix.o \
	$(obj).target/$(TARGET)/../src/uslscore/USThread_win32.o \
	$(obj).target/$(TARGET)/../src/uslscore/USTrig.o \
	$(obj).target/$(TARGET)/../src/uslscore/USTypedPtr.o \
	$(obj).target/$(TARGET)/../src/uslscore/USXmlReader.o \
	$(obj).target/$(TARGET)/../src/uslscore/USZip.o \
	$(obj).target/$(TARGET)/../src/uslscore/USZipFile.o \
	$(obj).target/$(TARGET)/../src/uslscore/uslscore-pch.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Default := 

LIBS := 

$(obj).target/libuslscore.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/libuslscore.a: LIBS := $(LIBS)
$(obj).target/libuslscore.a: TOOLSET := $(TOOLSET)
$(obj).target/libuslscore.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink)

all_deps += $(obj).target/libuslscore.a
# Add target alias
.PHONY: uslscore
uslscore: $(obj).target/libuslscore.a

# Add target alias to "all" target.
.PHONY: all
all: uslscore

