# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := work
DEFS_Default := 

# Flags passed to both C and C++ files.
CFLAGS_Default := 

# Flags passed to only C (and not C++) files.
CFLAGS_C_Default := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Default := 

INCS_Default := 

OBJS := $(obj).target/$(TARGET)/../src/work/main.o \
	$(obj).target/$(TARGET)/../src/work/work-bundled-lua.o \
	$(obj).target/$(TARGET)/../src/work/work-font-mipmap.o \
	$(obj).target/$(TARGET)/../src/work/work-moai-zipfs.o \
	$(obj).target/$(TARGET)/../src/work/work-pathfinding.o \
	$(obj).target/$(TARGET)/../src/work/work-zipfs-fscanf.o \
	$(obj).target/$(TARGET)/../src/work/work-zipfs-ungetc.o \
	$(obj).target/$(TARGET)/../src/work/work-zipfs.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/libmoaicore.a $(obj).target/libmoaiext-luaext.a $(obj).target/libbox2d.a $(obj).target/libchipmunk.a $(obj).target/libcontrib.a $(obj).target/libexpat.a $(obj).target/libfreetype.a $(obj).target/libglew.a $(obj).target/libjansson.a $(obj).target/libcrypto.a $(obj).target/libcurl.a $(obj).target/libjpg.a $(obj).target/libpng.a $(obj).target/libzlib.a $(obj).target/libssl.a $(obj).target/liblua-lib.a $(obj).target/libsqlite.a $(obj).target/libtinyxml.a $(obj).target/libuslscore.a $(obj).target/libzipfs.a $(obj).target/libtlsf.a $(obj).target/libluaext.a

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Default := 

LIBS := 

$(builddir)/work: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(builddir)/work: LIBS := $(LIBS)
$(builddir)/work: TOOLSET := $(TOOLSET)
$(builddir)/work: $(OBJS) $(obj).target/libmoaicore.a $(obj).target/libmoaiext-luaext.a $(obj).target/libbox2d.a $(obj).target/libchipmunk.a $(obj).target/libcontrib.a $(obj).target/libexpat.a $(obj).target/libfreetype.a $(obj).target/libglew.a $(obj).target/libjansson.a $(obj).target/libcrypto.a $(obj).target/libcurl.a $(obj).target/libjpg.a $(obj).target/libpng.a $(obj).target/libzlib.a $(obj).target/libssl.a $(obj).target/liblua-lib.a $(obj).target/libsqlite.a $(obj).target/libtinyxml.a $(obj).target/libuslscore.a $(obj).target/libzipfs.a $(obj).target/libtlsf.a $(obj).target/libluaext.a FORCE_DO_CMD
	$(call do_cmd,link)

all_deps += $(builddir)/work
# Add target alias
.PHONY: work
work: $(builddir)/work

# Add executable to "all" target.
.PHONY: all
all: $(builddir)/work

